name: Deploy Backend

on:
  push:
    paths:
      - 'server/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy with Railway
        uses: railwayapp/railway-deploy-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
